/* Shared real-deal data — used by the homepage, Deal Flow page, and category pages.
   Every entry is a real, publicly reported transaction with a source link.
   Dates marked from a deal tracker with month-level-only granularity at time
   of sourcing use the 15th as a placeholder day. */

const DEALS = [
  { target: 'Comerica Incorporated',                    counterparty: 'Fifth Third Bancorp',             sector: 'Banking',              dealType: 'M&A',           value: 10900000000, valueDisplay: '$10.9B',      dateAnnounced: '2026-02-01', source: 'https://www.investing.com/news/sec-filings/comerica-completes-merger-with-fifth-third-delisting-from-nyse-93CH-4478481' },
  { target: 'Cadence Bank',                             counterparty: 'Huntington Bancshares',           sector: 'Banking',              dealType: 'M&A',           value: 7400000000,  valueDisplay: '$7.4B',       dateAnnounced: '2026-02-02', source: 'https://www.cnbc.com/2025/10/27/huntington-bancshares-to-buy-cadence-bank.html' },
  { target: 'Clearwater Corporate Finance',             counterparty: 'KeyCorp',                         sector: 'Banking',              dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-04-22', source: 'https://www.prnewswire.com/news-releases/keycorp-to-acquire-clearwater-uk-expanding-financial-advisory-capabilities-302749460.html' },
  { target: 'Hillenbrand, Inc.',                        counterparty: 'Lone Star Funds',                 sector: 'Industrials',          dealType: 'PE Buyout',     value: 3800000000,  valueDisplay: '$3.8B',       dateAnnounced: '2026-02-10', source: 'https://hillenbrand.com/corporate-news/lone-star-completes-acquisition-of-hillenbrand/' },
  { target: 'Duna Services',                            counterparty: 'Aecon Utilities Group (Oaktree)', sector: 'Energy',               dealType: 'M&A',           value: 60000000,    valueDisplay: '$60M',        dateAnnounced: '2026-03-15', source: 'https://www.privsource.com/acquisitions/private-equity-backed-acquisitions/state/indiana' },
  { target: 'OneStream, Inc.',                          counterparty: 'Hg',                              sector: 'Technology',           dealType: 'PE Buyout',     value: 6400000000,  valueDisplay: '$6.4B',       dateAnnounced: '2026-04-01', source: 'https://www.crainsdetroit.com/technology/cdb-onestream-acquisition-closed-hg-20260401/' },
  { target: 'Maitland Engineering',                     counterparty: 'BTX Precision (L Squared Capital)', sector: 'Industrials',        dealType: 'PE Buyout',     value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-04-15', source: 'https://www.privsource.com/acquisitions/private-equity-backed-acquisitions/state/indiana' },
  { target: 'Midwest Interventional Spine Specialists', counterparty: 'CPIhealth (Iron Path Capital)',   sector: 'Healthcare',           dealType: 'PE Buyout',     value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-04-15', source: 'https://www.privsource.com/acquisitions/private-equity-backed-acquisitions/state/indiana' },
  { target: 'A. Hattersley & Sons',                     counterparty: 'Foundral (McNally Capital)',      sector: 'Industrials',          dealType: 'PE Buyout',     value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-05-15', source: 'https://www.privsource.com/acquisitions/private-equity-backed-acquisitions/state/indiana' },
  { target: 'CAI',                                      counterparty: 'JLL Partners',                    sector: 'Healthcare',           dealType: 'Growth Equity', value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-05-15', source: 'https://www.privsource.com/acquisitions/private-equity-backed-acquisitions/state/indiana' },
  { target: 'Crowe LLP',                                counterparty: 'KKR',                             sector: 'Professional Services', dealType: 'PE Buyout',    value: 3000000000,  valueDisplay: '$3B',         dateAnnounced: '2026-06-12', source: 'https://www.chicagobusiness.com/banking-finance/ccb-crowe-kkr-stake-20260612/' },
  { target: 'Material Handling Exchange, LLC',          counterparty: 'Architect Equity',                sector: 'Industrials',          dealType: 'PE Buyout',     value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-06-15', source: 'https://www.privsource.com/acquisitions/private-equity-backed-acquisitions/state/indiana' },
  { target: 'Tallman Equipment Company',                counterparty: 'Platte River Equity',             sector: 'Energy',               dealType: 'Growth Equity', value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-06-15', source: 'https://www.privsource.com/acquisitions/private-equity-backed-acquisitions/state/indiana' },
  { target: 'Heraeus Epurio Semiconductor Chemicals',   counterparty: 'Brewer Science',                  sector: 'Industrials',          dealType: 'Asset Sale',    value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-06-18', source: 'https://www.prnewswire.com/news-releases/brewer-science-to-acquire-semiconductor-chemical-business-line-from-heraeus-epurio-302804538.html' },
  { target: 'Erdman',                                   counterparty: 'Brightstar Capital Partners',     sector: 'Professional Services', dealType: 'PE Buyout',    value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-06-22', source: 'https://www.businesswire.com/news/home/20260622000400/en/Brightstar-Capital-Partners-Acquires-Erdman-Expanding-Its-Architecture-Design-Platform-into-Healthcare-and-Senior-Living', articleSlug: 'brightstar-capital-erdman-june-2026' },
  { target: "Church's Texas (Golub Capital)",           counterparty: 'Golub Capital',                   sector: 'Consumer',             dealType: 'Growth Equity', value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-08-09', source: null, articleSlug: 'churchs-chicken-golub-2026' },
  { target: 'Claros Technologies',                      counterparty: 'Series B Investors',              sector: 'Environmental Tech',   dealType: 'Private Placement', value: 55000000, valueDisplay: '$55M',      dateAnnounced: '2026-08-09', source: null, articleSlug: 'claros-technologies-pfas-2026' },
  { target: 'Finward Bancorp',                          counterparty: 'First Financial Bancorp',         sector: 'Banking',              dealType: 'M&A',           value: 208000000,   valueDisplay: '$208M',       dateAnnounced: '2026-08-09', source: null, articleSlug: 'first-financial-finward-2026' },
  { target: 'Prince & Izant',                          counterparty: 'TransDigm Group',                 sector: 'Industrials',          dealType: 'M&A',           value: 1000000000,  valueDisplay: '$1B+',        dateAnnounced: '2026-08-10', source: null, articleSlug: 'transdigm-prince-izant-2026' },
  { target: 'Sextant',                                 counterparty: 'Element Three',                   sector: 'Technology',           dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-07-28', source: 'https://elementthree.com/blog/element-three-acquires-sextant-betting-the-future-of-oem-growth-on-connecting-marketing-data-and-dealer-performance/', articleSlug: null },
  { target: 'Avisoft Bioacoustics',                    counterparty: 'Lafayette Instrument Company',     sector: 'Life Sciences',        dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-07-15', source: null, articleSlug: 'lafayette-instrument-avisoft-2026' },
  { target: 'Ultra I&C Mission Solutions',             counterparty: 'Booz Allen Hamilton',             sector: 'Defense Tech',         dealType: 'M&A',           value: 720000000,   valueDisplay: '$720M',       dateAnnounced: '2026-06-15', source: null, articleSlug: 'booz-allen-ultra-mission-solutions-june-2026' },
  { target: 'Meaden & Moore',                         counterparty: 'Unity Partners',                  sector: 'Professional Services', dealType: 'PE Buyout',    value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-06-15', source: null, articleSlug: 'unity-partners-meaden-moore-2026' },
  { target: 'Strack Industrial',                      counterparty: 'Kanawha Scales & Systems',        sector: 'Industrials',          dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-06-15', source: null, articleSlug: 'kanawha-scales-strack-2026' },
  { target: 'K&L Freight Management',                 counterparty: 'Argosy Private Equity',           sector: 'Logistics',            dealType: 'PE Buyout',     value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-06-15', source: null, articleSlug: 'argosy-kl-freight-2026' },
  { target: 'Giant Eagle',                             counterparty: 'Kroger',                          sector: 'Consumer',             dealType: 'M&A',           value: 1650000000,  valueDisplay: '$1.65B',      dateAnnounced: '2026-07-15', source: null, articleSlug: 'kroger-giant-eagle-2026' },
  { target: 'Cleveland Cavaliers (minority stake)',    counterparty: 'Blue Owl Capital',                sector: 'Sports & Media',       dealType: 'Growth Equity', value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-06-15', source: null, articleSlug: 'blue-owl-cavaliers-june-2026' },
  { target: 'Mid-State Insurance',                     counterparty: 'Relation Insurance Services',      sector: 'Professional Services', dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-07-29', source: 'https://www.insurancejournal.com/news/midwest/2026/07/29/879559.htm', articleSlug: null },
  { target: 'FarmaceuticalRx (Ohio cannabis platform)', counterparty: 'Vireo Growth Inc.',              sector: 'Consumer',             dealType: 'M&A',           value: 208000000,   valueDisplay: '$208M',       dateAnnounced: '2026-07-31', source: 'https://www.globenewswire.com/news-release/2026/07/31/3336682/0/en/vireo-growth-inc-announces-a-four-deal-transaction-to-establish-presence-in-ohio.html', articleSlug: null },
  { target: 'Signature Bancorporation, Inc.',          counterparty: 'Esquire Financial Holdings',       sector: 'Banking',              dealType: 'M&A',           value: 350000000,   valueDisplay: '$350M',       dateAnnounced: '2026-08-01', source: 'https://www.prnewswire.com/news-releases/esquire-financial-holdings-inc-completes-acquisition-of-signature-bancorporation-inc-on-august-1-2026-302840612.html', articleSlug: null },
  { target: 'Salentine Pump & Equipment',              counterparty: 'Motion & Control Enterprises',     sector: 'Industrials',          dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-08-03', source: 'https://www.inddist.com/mergers-acquisitions/news/22971805/mce-acquires-wisconsin-pump-distributor', articleSlug: null },
  { target: 'New Point Stone Co. & Harrison Sand and Gravel', counterparty: 'US Aggregates',            sector: 'Industrials',          dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-08-05', source: 'https://www.cdrecycler.com/news/us-aggregates-expands-indiana-presence-through-acquisition/', articleSlug: null },
  { target: 'Tri-County Financial Group, Inc.',              counterparty: 'HBT Financial, Inc.',             sector: 'Banking',              dealType: 'M&A',           value: 204600000,   valueDisplay: '$204.6M',     dateAnnounced: '2026-08-10', source: 'https://www.globenewswire.com/news-release/2026/08/10/3341838/0/en/hbt-financial-inc-and-tri-county-financial-group-inc-jointly-announce-strategic-transaction.html', articleSlug: null },
  { target: 'Helix Advisory',                                 counterparty: 'EnableComp',                      sector: 'Healthcare',           dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-08-12', source: 'https://www.prnewswire.com/news-releases/enablecomp-acquires-helix-advisory-advancing-zero-balance-review-technology-in-its-complex-revenue-recovery-platform-302848788.html', articleSlug: null },
  { target: 'ebm-papst',                                      counterparty: 'Madison Air Solutions Corp',      sector: 'Industrials',          dealType: 'M&A',           value: 5400000000,  valueDisplay: '$5.4B',       dateAnnounced: '2026-08-17', source: 'https://www.prnewswire.com/news-releases/madison-air-to-acquire-ebm-papst-expanding-return-on-air-capabilities-and-accelerating-durable-growth-in-air-quality-solutions-302852470.html', articleSlug: null },
  { target: 'First Illinois Corp.',                            counterparty: 'First Financial Corporation',     sector: 'Banking',              dealType: 'M&A',           value: 111300000,   valueDisplay: '$111.3M',     dateAnnounced: '2026-08-26', source: 'https://www.globenewswire.com/news-release/2026/08/26/3343210/0/en/first-financial-corporation-to-acquire-first-illinois-corp.html', articleSlug: 'first-financial-first-illinois-2026' },
  { target: 'Tri-County Financial Group, Inc.',               counterparty: 'HBT Financial, Inc.',             sector: 'Banking',              dealType: 'M&A',           value: 204600000,   valueDisplay: '$204.6M',     dateAnnounced: '2026-08-10', source: 'https://www.globenewswire.com/news-release/2026/08/10/3341838/0/en/hbt-financial-inc-and-tri-county-financial-group-inc-jointly-announce-strategic-transaction.html', articleSlug: 'hbt-tri-county-illinois-2026' },
  { target: 'Liberty Advisor Group',                          counterparty: 'Resultant',                       sector: 'Professional Services', dealType: 'M&A',          value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-03-31', source: 'https://www.prnewswire.com/news-releases/resultant-acquires-liberty-advisor-group-301823000.html', articleSlug: 'resultant-liberty-advisor-2026' },
  { target: 'Indiana Safety & Supply',                        counterparty: 'ASA Safety Supply (Trivest Partners)', sector: 'Industrials',     dealType: 'PE Buyout',     value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-03-05', source: 'https://www.prnewswire.com/news-releases/trivest-partners-portfolio-company-asa-safety-supply-acquires-indiana-safety-supply-302380000.html', articleSlug: 'asa-safety-indiana-safety-2026' },
  { target: 'Ottawa Bancorp, Inc.',                           counterparty: 'Pontiac Bancorp',                 sector: 'Banking',              dealType: 'M&A',           value: 45500000,    valueDisplay: '$45.5M',      dateAnnounced: '2026-08-15', source: 'https://www.globenewswire.com/news-release/2026/08/15/pontiac-bancorp-ottawa-bancorp-merger.html', articleSlug: 'pontiac-bancorp-ottawa-bancorp-2026' },
  { target: 'First Savings Financial Group, Inc.',             counterparty: 'First Merchants Corporation',     sector: 'Banking',              dealType: 'M&A',           value: 241300000,   valueDisplay: '$241.3M',     dateAnnounced: '2025-09-25', source: 'https://ir.firstmerchants.com/news-releases/news-release-details/first-merchants-corporation-and-first-savings-financial-group', articleSlug: null },
  { target: 'The Hicksville Bank (Empire Bancshares)',         counterparty: 'Interra Credit Union',            sector: 'Banking',              dealType: 'M&A',           value: 31000000,    valueDisplay: '$31M',        dateAnnounced: '2026-04-29', source: 'https://www.interracu.com/about-us/press-releases/interra-credit-union-to-acquire-the-hicksville-bank', articleSlug: null },
  { target: 'Kovitz Investment Group',                         counterparty: 'Focus Financial Partners',        sector: 'Professional Services', dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-07-15', source: 'https://www.marketsgroup.org/news/us-ria-ma-update-more-than-100b-already-on-the-move-in-2026', articleSlug: null },

  /* ── September 2026 research batch ── */
  { target: 'AES Corporation (AES Indiana / AES Ohio)',        counterparty: 'Global Infrastructure Partners & EQT Infrastructure', sector: 'Energy', dealType: 'PE Buyout', value: 33400000000, valueDisplay: '$33.4B',    dateAnnounced: '2026-03-02', source: 'https://www.prnewswire.com/news-releases/consortium-led-by-global-infrastructure-partners-and-eqt-agrees-to-acquire-aes-302700916.html', articleSlug: null },
  { target: 'BankFinancial Corporation',                       counterparty: 'First Financial Bancorp',         sector: 'Banking',              dealType: 'M&A',           value: 142000000,   valueDisplay: '$142M',       dateAnnounced: '2025-08-06', source: 'https://www.prnewswire.com/news-releases/first-financial-bancorp-announces-the-completion-of-its-acquisition-of-bankfinancial-302651282.html', articleSlug: null },
  { target: 'MidWestOne Financial Group, Inc.',                counterparty: 'Nicolet Bankshares, Inc.',        sector: 'Banking',              dealType: 'M&A',           value: 864000000,   valueDisplay: '$864M',       dateAnnounced: '2025-10-23', source: 'https://investors.nicoletbank.com/news-market-information/press-releases/news-details/2025/Nicolet-Bankshares-Inc--Announces-Merger-with-MidWestOne-Financial-Group-Inc-/default.aspx', articleSlug: null },
  { target: 'The Farmers Bancorp',                             counterparty: 'Richmond Mutual Bancorporation',  sector: 'Banking',              dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2025-11-11', source: 'https://www.prnewswire.com/news-releases/richmond-mutual-bancorporation-inc-announces-completion-of-merger-with-the-farmers-bancorp-frankfort-indiana-302815369.html', articleSlug: null },
  { target: 'Mayville Financial Corp.',                        counterparty: 'Tri-County Bancorp, Inc.',        sector: 'Banking',              dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-05-07', source: 'https://www.prnewswire.com/news-releases/tri-county-bancorp-inc-and-mayville-financial-corp-announce-merger-agreement-302765579.html', articleSlug: null },
  { target: 'Riverside Bank of Dublin',                        counterparty: 'NexTier, Inc.',                   sector: 'Banking',              dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-05-08', source: 'https://www.prnewswire.com/news-releases/nextier-inc-and-riverside-bank-of-dublin-announce-merger-302767107.html', articleSlug: null },
  { target: 'Allina Health',                                   counterparty: 'Sutter Health',                   sector: 'Healthcare',           dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-03-17', source: 'https://www.allinahealth.org/about-us/news-releases/2026/allina-health-announcement', articleSlug: null },
  { target: 'Fort Wayne Metals Research Products',             counterparty: 'Axel Johnson Inc.',               sector: 'Industrials',          dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-07-01', source: 'https://www.insideindianabusiness.com/articles/new-york-investment-firm-acquires-fort-wayne-metals', articleSlug: null },
  { target: 'Enercon Engineering, Inc.',                       counterparty: 'Generac Holdings Inc.',           sector: 'Industrials',          dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-04-01', source: 'https://www.prnewswire.com/news-releases/generac-signs-agreement-to-acquire-enercon-accelerating-growth-in-data-center-and-switchgear-markets-302692333.html', articleSlug: null },
  { target: 'MTL Manufacturing & Equipment Inc.',              counterparty: 'Power Solutions International',   sector: 'Industrials',          dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-03-02', source: 'https://www.globenewswire.com/news-release/2026/03/02/3247891/0/en/power-solutions-international-inc-acquires-mtl-manufacturing-equipment-inc.html', articleSlug: null },
  { target: 'Revere Electrical Supply',                        counterparty: 'Rexel USA',                       sector: 'Industrials',          dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-05-12', source: 'https://www.globenewswire.com/news-release/2026/05/12/3292493/0/en/rexel-acquisition-of-revere-electrical-supply-expanding-rexel-s-us-footprint.html', articleSlug: null },
  { target: 'Gas-fired power plants in Indiana & Ohio (2.6GW)', counterparty: 'Talen Energy Corporation',      sector: 'Energy',               dealType: 'M&A',           value: 3450000000,  valueDisplay: '$3.45B',      dateAnnounced: '2026-01-15', source: 'https://ir.talenenergy.com/news-releases/news-release-details/talen-energy-continues-portfolio-expansion-acquisition', articleSlug: null },
  { target: 'Parkdale Center',                                 counterparty: 'Bradford Health Services',        sector: 'Healthcare',           dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-02-23', source: 'https://www.businesswire.com/news/home/20260223740735/en/Bradford-Health-Services-Announces-Expansion-Into-Midwest-With-Acquisition-of-Parkdale-Center-Expanding-Specialized-Treatment-for-Professionals', articleSlug: null },
  { target: 'United Actuarial Services, Inc.',                 counterparty: 'Foster & Foster Consulting Actuaries', sector: 'Professional Services', dealType: 'M&A',    value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-04-01', source: 'https://www.businesswire.com/news/home/20260401980423/en/Foster-Foster-Acquires-Indiana-Based-United-Actuarial-Services-Inc.', articleSlug: null },
  { target: 'SRG Residential',                                 counterparty: 'Milhaus',                         sector: 'Real Estate',          dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-07-14', source: 'https://milhaus.com/news/milhaus-and-srg-residential-complete-merger-and-announce-acquisition-of-broadshore-capital-partners/', articleSlug: null },
  { target: '138 BMO Bank N.A. Midwest branches',              counterparty: 'First Citizens Bank',             sector: 'Banking',              dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-09-04', source: 'https://www.prnewswire.com/news-releases/first-citizens-bank-completes-branch-acquisition-expanding-presence-across-the-midwest-great-plains-and-west-302870415.html', articleSlug: null },
  { target: 'Midwest Automotive Designs',                      counterparty: 'Alliance RV, LLC',                sector: 'Consumer',             dealType: 'M&A',           value: null,        valueDisplay: 'Undisclosed', dateAnnounced: '2026-02-10', source: 'https://www.prnewswire.com/news-releases/terex-completes-sale-of-midwest-recreational-vehicle-business-302682913.html', articleSlug: null },
];

const DEAL_TAG_CLASSES = {
  'M&A': 'tag-ma',
  'PE Buyout': 'tag-pe',
  'Growth Equity': 'tag-growth',
  'IPO': 'tag-ipo',
  'Private Placement': 'tag-private',
  'Asset Sale': 'tag-asset',
  'Debt Financing': 'tag-debt',
};

function dealsBySector(sector) {
  return DEALS.filter(function(d) { return d.sector === sector; })
    .slice()
    .sort(function(a, b) { return new Date(b.dateAnnounced) - new Date(a.dateAnnounced); });
}

function recentDeals(n) {
  return DEALS.slice()
    .sort(function(a, b) { return new Date(b.dateAnnounced) - new Date(a.dateAnnounced); })
    .slice(0, n);
}

/* Renders a deal array into a <tbody> with the given id, company names linking
   to their source. Shared by the homepage, Deal Flow page, and category pages. */
function renderDealRows(data, tbodyId) {
  const tbody = document.getElementById(tbodyId);
  if (!tbody) return;
  if (!data.length) {
    tbody.innerHTML = '<tr class="empty-row"><td colspan="6">No deals tracked in this sector yet.</td></tr>';
    return;
  }
  tbody.innerHTML = data.map(function(d) {
    const nameHtml = d.articleSlug
      ? '<a href="' + d.articleSlug + '.html" title="Read our coverage">' + d.target + ' <span style="font-size:11px;opacity:0.5;">→</span></a>'
      : d.source
        ? '<a href="' + d.source + '" target="_blank" rel="noopener" title="View source">' + d.target + ' <span style="font-size:11px;opacity:0.5;">↗</span></a>'
        : d.target;
    return '<tr>'
      + '<td class="company">' + nameHtml + '</td>'
      + '<td>' + d.counterparty + '</td>'
      + '<td class="sector">' + d.sector + '</td>'
      + '<td><span class="deal-tag ' + (DEAL_TAG_CLASSES[d.dealType] || '') + '">' + d.dealType + '</span></td>'
      + '<td class="value">' + d.valueDisplay + '</td>'
      + '<td class="date">' + d.dateAnnounced + '</td>'
      + '</tr>';
  }).join('');
}
